[package]
name = "learn"
version = "0.1.0"
authors = ["gpwclark <gpwclark@gmail.com>"]

[dependencies]
enum-display-derive = "0.1.1"
rand = "0.5.5"
confy = "0.3.1"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
